language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - unset CI 
  - npm run build
before_install:
  - cd quick_doc
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token "1//0foipgMoUZFePCgYIARAAGA8SNwF-L9IrNVNiWDacjuQssU8NDCjQI1mSQvQZNKvGEGuhP15v9R95vJsnQSveEacZxuw-2cyEl_s" --non-interactive